export const QUESTIONNAIRES = {
  pre: {
    title: "Pre-task questionnaire",
    description: "Learner expectations and attitudes before starting the educational escape room.",
    fields: [
      { id: "participantCode", label: "Participant code / alias", type: "text", required: true },
      { id: "courseGroup", label: "Course / group", type: "text", required: true },
      { id: "previousEscapeRooms", label: "Previous experience with educational escape rooms", type: "select", options: ["None", "A little", "Some", "A lot"] },
      { id: "previousVibeCoding", label: "Previous experience with AI-generated or vibe-coded learning resources", type: "select", options: ["None", "A little", "Some", "A lot"] },
      { id: "phoneticsConfidence", label: "Confidence with English phonetics", type: "likert" },
      { id: "ipaConfidence", label: "Confidence with IPA transcription", type: "likert" },
      { id: "gamifiedUsefulness", label: "Perceived usefulness of gamified learning", type: "likert" },
      { id: "preAnxiety", label: "Perceived anxiety before starting", type: "likert" },
      { id: "expectations", label: "Expectations about the activity", type: "textarea" },
      { id: "openExpectation", label: "What do you expect from this resource?", type: "textarea" },
    ],
    likert: [
      "I feel confident identifying English phonetic symbols.",
      "I feel confident transcribing English words using IPA.",
      "I think gamified resources can support language learning.",
      "I am familiar with digital escape rooms as learning tools.",
      "I am familiar with AI-assisted or vibe-coded educational resources.",
      "I expect this activity to be engaging.",
      "I expect this activity to help me practise English phonetics.",
      "I feel anxious about completing this activity.",
      "I prefer interactive resources to traditional worksheets.",
      "I understand that my anonymised responses may be used for teaching/research purposes.",
    ],
  },
  post: {
    title: "Post-task questionnaire",
    description: "Learner experience after completing or exiting the escape room.",
    fields: [
      { id: "overallExperience", label: "Overall experience", type: "likert" },
      { id: "usability", label: "Usability", type: "likert" },
      { id: "visualDesign", label: "Visual design", type: "likert" },
      { id: "engagement", label: "Engagement", type: "likert" },
      { id: "perceivedLearning", label: "Perceived learning", type: "likert" },
      { id: "cognitiveLoad", label: "Cognitive load / difficulty", type: "likert" },
      { id: "gamificationUsefulness", label: "Perceived usefulness of gamification", type: "likert" },
      { id: "vibeCodingPerception", label: "Perception of vibe-coded / AI-assisted educational resources", type: "likert" },
      { id: "suggestions", label: "Suggestions for improvement", type: "textarea" },
      { id: "openComments", label: "Open comments", type: "textarea" },
    ],
    likert: [
      "The resource was easy to navigate.",
      "The visual design helped me stay engaged.",
      "The escape-room format made the phonetics practice more motivating.",
      "The activity helped me practise IPA transcription.",
      "The activity helped me reflect on voicing and manner of articulation.",
      "The level of difficulty was appropriate.",
      "The instructions were clear.",
      "The game elements supported learning rather than distracting from it.",
      "I would like to use similar resources in other language-learning contexts.",
      "This resource changed my perception of AI-assisted or vibe-coded educational materials.",
      "I consider this type of resource useful for university-level English learning.",
      "I would recommend this activity to other students.",
    ],
    openQuestions: [
      "What did you like most about the resource?",
      "What was difficult or confusing?",
      "What would you improve?",
      "How did the escape-room format affect your motivation?",
      "What is your opinion of using vibe-coded educational resources in university teaching?",
    ],
  },
};

export const LIKERT_LABELS = {
  1: "Strongly disagree",
  2: "Disagree",
  3: "Neither agree nor disagree",
  4: "Agree",
  5: "Strongly agree",
};
